ClassLibrary/ClassLibrary.csproj, ClassLibrary/clsStaff.cs, Testing2/TestingStaff.csproj, Testing2/tstStaff.cs
=> Added testing for clsStaff

ClassLibrary/ClassLibrary.csproj, ClassLibrary/clsOrder.cs, Testing5/TestingOrder.csproj, Testing5/tstOrder.cs
=> Added testing for order class

ClassLibrary/ClassLibrary.csproj, ClassLibrary/clsAddress.cs, Testing3/TestingSupplier.csproj, Testing3/tstSupplier.cs
=> Added Testing for supplier class

ClassLibrary/clsStaff.cs, Testing2/tstStaff.cs
=> Entered all testing for clsStaff instances in tstStaff

ClassLibrary/clsOrder.cs, Testing5/tstOrder.cs
=> Added testing for clsOrder properties

Testing4/Properties/AssemblyInfo.cs, Testing4/TestingStock.csproj, Testing4/tstStock.cs
=> created clsStock

Testing4/tstStock.cs
=> entered clsStocks

AdminSystem/OrderDataEntry.aspx, AdminSystem/OrderDataEntry.aspx.cs, AdminSystem/OrderViewer.aspx.cs, ClassLibrary/clsOrder.cs, Skeleton.sln, Testing5/tstOrder.cs
=> Added the presentation layer for Order data entry

AdminSystem/StaffDataEntry.aspx, AdminSystem/StaffDataEntry.aspx.cs, AdminSystem/StaffViewer.aspx, Skeleton.sln
still need to finish the reference part
=> made changes to the middle layer

ClassLibrary/clsCustomer.cs, Testing1/tstCustomer.cs
=> changed property names

ClassLibrary/clsOrder.cs, Testing5/tstOrder.cs
=> Added find method and testing for clsOrder

AdminSystem/OrderDataEntry.aspx, AdminSystem/OrderDataEntry.aspx.cs, ClassLibrary/clsOrder.cs, Testing5/tstOrder.cs
=> Added find button to Order presentation layer

AdminSystem/CustomerDataEntry.aspx, AdminSystem/CustomerDataEntry.aspx.cs, AdminSystem/CustomerViewer.aspx.cs
=> redone prac 8

ClassLibrary/clsCustomer.cs, Testing1/tstCustomer.cs
=> Created all test methods and some get set properties

ClassLibrary/clsCustomer.cs, Testing1/tstCustomer.cs
=> completed practical 9a

ClassLibrary/clsOrder.cs, Testing5/tstOrder.cs
=> Added validation testing for clsOrder and Afnan's web designing skills

AdminSystem/OrderDataEntry.aspx, AdminSystem/OrderDataEntry.aspx.cs
=> Added validation to the presentation layer for clsOrder

AdminSystem/CustomerList.aspx, AdminSystem/CustomerList.aspx.cs, ClassLibrary/clsCustomerCollection.cs, Testing1/tstCustomer.cs, Testing1/tstCustomerCollection.cs
=> finished prac 12

AdminSystem/StockConfirmDelete.aspx, AdminSystem/StockConfirmDelete.aspx.cs, AdminSystem/StockDataEntry.aspx.cs, AdminSystem/StockList.aspx, AdminSystem/StockList.aspx.cs, ClassLibrary/ClsStockCollection.cs, Testing4/tstStockCollection.cs
=> 14a error free

AdminSystem/OrderDataEntry.aspx, AdminSystem/OrderDataEntry.aspx.cs, AdminSystem/OrderList.aspx, AdminSystem/OrderList.aspx.cs, AdminSystem/OrderViewer.aspx, ClassLibrary/ClassLibrary.csproj, ClassLibrary/clsOrder.cs, ClassLibrary/clsOrderCollection.cs, Testing5/TestingOrder.csproj, Testing5/tstOrder.cs, Testing5/tstOrderCollection.cs
=> Completed practical 13

ClassLibrary/clsCustomer.cs, Testing1/tstCustomer.cs
my guy top man good job proud of ypu
=> validation changes

AdminSystem/StaffList.aspx, AdminSystem/StockConfirmDelete.aspx, AdminSystem/StockConfirmDelete.aspx.cs, AdminSystem/StockList.aspx, AdminSystem/StockList.aspx.cs, ClassLibrary/ClsStockCollection.cs, ClassLibrary/clsDataConnection.cs, Testing4/tstStockCollection.cs
=> 14 completed

ClassLibrary/ClsStockCollection.cs, Testing4/tstStockCollection.cs
=> 14b complete

AdminSystem/StockList.aspx, AdminSystem/StockList.aspx.cs, AdminSystem/StockLogin.aspx, AdminSystem/StockLogin.aspx.cs, ClassLibrary/ClassLibrary.csproj, ClassLibrary/clsStockUser.cs, Testing2/tstStaffCollection.cs, Testing4/TestingStock.csproj, Testing4/tstStockUser.cs
=> 15 complete

AdminSystem/OrderList.aspx, AdminSystem/OrderList.aspx.cs, ClassLibrary/clsOrderCollection.cs, Testing5/tstOrderCollection.cs
=> p14b complete

AdminSystem/OrderConfirmDelete.aspx, AdminSystem/OrderConfirmDelete.aspx.cs, AdminSystem/OrderDataEntry.aspx, AdminSystem/OrderDataEntry.aspx.cs, AdminSystem/OrderLogin.aspx, AdminSystem/OrderLogin.aspx.cs, AdminSystem/Web.Debug.config, AdminSystem/Web.config, ClassLibrary/ClassLibrary.csproj, ClassLibrary/clsOrderUser.cs, Testing5/TestingOrder.csproj, Testing5/tstOrderUser.cs
=> p15 complete

AdminSystem/OrderDataEntry.aspx, AdminSystem/OrderDataEntry.aspx.cs, AdminSystem/OrderList.aspx, AdminSystem/OrderList.aspx.cs, AdminSystem/OrderLogin.aspx, AdminSystem/OrderLogin.aspx.cs
=> p16 completed

ClassLibrary/ClsStockCollection.cs
=> changes made error free

AdminSystem/StockList.aspx, AdminSystem/StockList.aspx.cs
=> changes made
